pay/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('final/', views.final, name='final'),
    path('', views.Pay.as_view(), name='home'),
]

product/urls.py
from django.urls import path
from .views import (
	ListPage,
	DetailPage,
	create_cart,
	# OrderSummaryView,
	clear,
	SummaPage,
)
from django.contrib.auth.decorators import login_required
app_name = 'core'

urlpatterns = [
	path('create-cart/<slug>/', login_required(create_cart), name='create-cart'),
	path('summary/', login_required(SummaPage), name='summary'),
	path('clear/', clear, name='clear'),
	path('<slug>/', DetailPage.as_view(), name='detail-product'),
	path('', ListPage.as_view(), name='list-product'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pay/', include('pay.urls')),
    path('api/v1/', include(('api_product.urls', 'api-product'), namespace='api-product')),
    path('api/v1/accounts/', include(('api_accounts.urls', 'api-accounts'), namespace='api-accounts')),
    path('', include(('product.urls', 'product'), namespace='product')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models

from django.conf import settings


from django.contrib.auth import get_user_model
User = get_user_model()

class Product(models.Model):
	title = models.CharField(max_length=400, default=0)
	desc = models.CharField(max_length=400, default=0)
	user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,)
	price = models.IntegerField(default=0)
	image = models.ImageField(upload_to = '', default = 'none/no-img.jpg')
	slug = models.SlugField()
	def __str__(self):
		return self.title


class Cart(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,)
	finish = models.BooleanField(default=False)
	def __str__(self):
		return self.product.title


class Order(models.Model):
	author = models.IntegerField(default=0)
	carts = models.ManyToManyField(Cart)
	finish = models.BooleanField(default=False)
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
	pay_stripe = models.ForeignKey('PayStripe', on_delete=models.SET_NULL, blank=True, null=True)

	def __str__(self):
		return self.user.username

	def get_sum(self):
		total = 0
		for order_item in self.carts.all():
			total = order_item.product.price + total
		return total

	def get_item_count(self):
		result = self.carts.all().count()
		return result


class PayStripe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    stripe_id = models.CharField(max_length=100)
    total = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

product/views.py
from django.views.generic import (
	ListView, 
	DetailView, 
	View
)


from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.shortcuts import redirect
from django.utils import timezone

from .models import Product, Cart, Order



from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404



class ListPage(ListView):
	model = Product
	paginate_by = 4
	template_name = "product/list.html"



class DetailPage(DetailView):
	model = Product
	template_name = "product/detail.html"



def create_cart(request, slug):
	product = get_object_or_404(Product, slug=slug)
	user_login = request.user
	cart_single = Cart.objects.create(
		product=product,
		user=user_login,
	)
	if Order.objects.filter(user=request.user, finish=False).exists():
		order = Order.objects.get(user=user_login, finish=False)
	else:
		order = Order.objects.create(user=user_login)
	order.carts.add(cart_single)

	return redirect("core:detail-product", slug=slug)



def clear(request):
	Order.objects.filter(user=request.user).delete()
	Cart.objects.filter(user=request.user).delete()
	return redirect("/")




def SummaPage(request):
	if Order.objects.filter(user=request.user, finish=False).exists():
		order = Order.objects.get(user=request.user, finish=False)
		context = {
		'object': order
		}
		return render(request, 'product/order.html', context)
	else:
		messages.error(request, "Cart is empty")
		return redirect("/")

templates/product/detail.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
	<h1>{{ object.title }}</h1>
	Description: <b>{{ object.desc }}</b><br>
	Price: <b>{{ object.price }} $</b><br><br>
	<img src="{{ MEDIA_URL }}{{ object.image.url }}"  alt="img"><br><br>
	<a href="{% url 'core:create-cart' object.slug %}"><button type="button" class="btn btn-success">+ To Cart</button></a>
</div>
{% endblock content %}

templates/product/list.html
{% extends "base.html" %}

{% block content %}


<div class="container">



<div class="row">


{% for item in object_list %}
<div class="col-lg-3 col-md-6 mb-4">
<div class="card">
  <a href="{%url 'product:detail-product' item.slug %}"><img src="{{ MEDIA_URL }}{{ item.image.url }}" class="card-img-top" alt="img"></a>
  <div class="card-body">
    <a href="{%url 'product:detail-product' item.slug %}"><h5 class="card-title">{{ item.title }}</h5></a>
    <p class="card-text">{{ item.desc }}</p>
    <button class="btn btn-warning">{{ item.price }}$</button>
  </div>
</div>
</div>



{% endfor %}


</div>

</div>



{% if page_obj.has_other_pages %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&laquo;</a>
            </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active">
                    <a class="page-link">{{ i }} <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&raquo;</a>
            </li>
        {% endif %}
    </ul>
{% endif %}







{% endblock content %}

templates/product/order.html
{% extends "base.html" %}
{% block content %}
  <main>
    <div class="container">
      
<h3><center>Order Final</center></h3>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>


     {% for order_item in object.carts.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.product.title }}</td>
            <td>{{ order_item.product.desc|slice:"50" }}</td>
            <td>{{ order_item.product.price }}$</td>
            
        </tr>
    {% endfor %}


        <tr>
            <td colspan="3"><b>Order Total</b></td>
            <td><b>{{ object.get_sum }} $</b></td>
        </tr>
     

  </tbody>
</table>

<a class='btn btn-danger float-left' href='/clear/'>Clear</a>
<a class='btn btn-success float-right ml-2' href='/pay/'>Pay visa</a>







{% endblock content %}