pay/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('final/', views.final, name='final'),
    path('', views.Pay.as_view(), name='home'),
]

product/urls.py
from django.urls import path
from .views import (
	ListPage,
	DetailPage,
	create_cart,
	# OrderSummaryView,
	clear,
	SummaPage,
)
from django.contrib.auth.decorators import login_required
app_name = 'core'

urlpatterns = [
	path('create-cart/<slug>/', login_required(create_cart), name='create-cart'),
	path('summary/', login_required(SummaPage), name='summary'),
	path('clear/', clear, name='clear'),
	path('<slug>/', DetailPage.as_view(), name='detail-product'),
	path('', ListPage.as_view(), name='list-product'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pay/', include('pay.urls')),
    path('api/v1/', include(('api_product.urls', 'api-product'), namespace='api-product')),
    path('api/v1/accounts/', include(('api_accounts.urls', 'api-accounts'), namespace='api-accounts')),
    path('', include(('product.urls', 'product'), namespace='product')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    


{% load static %}


<link rel="stylesheet" href='{% static "/bootstrap/css/bootstrap.min.css" %}' integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<script src='{% static "/bootstrap/js/bootstrap.min.js" %}' integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>





  </head>
  <body>


<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href="{%url 'product:list-product' %}">KungFu Shop</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{%url 'product:summary' %}">{% load cart_item %} {% get_cart_item %} | Cart</a>

  </li>
  {% if request.user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{%url 'account_logout' %}">Logout</a>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'account_signup'%}">Register</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'account_login'%}">Login</a>
  </li>
  {% endif %}
</ul>


    <div class="container">
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    <hr>
    {% endif %}

    


    {% block content %}
    {% endblock %}

    {% endblock %}
    {% block extra_body %}
    {% endblock %}

    </div>
  </body>
</html>